# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbiage',
            name='text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
