# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160910_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbiage',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
